function M = Mfunc2(in1)
%MFUNC2
%    M = MFUNC2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Jul-2016 16:58:55

M = reshape([1.0./6.0,0.0,0.0,0.0,1.0./6.0,0.0,0.0,0.0,1.0./6.0],[3,3]);
