function M = Mfunc2(in1)
%MFUNC2
%    M = MFUNC2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    29-Jun-2016 11:27:04

M = reshape([1.0./1.8e1,0.0,0.0,0.0,1.0./1.8e1,0.0,0.0,0.0,1.0./1.8e1],[3,3]);
