function N = Nfunc2(in1,in2)
%NFUNC2
%    N = NFUNC2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    29-Jun-2016 11:27:04

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
N = [q1.*1.9e3-3.24635e2;q2.*1.9e3-3.24635e2;q3.*1.9e3-3.24635e2];
