%CREATEFIT(P,H,F)
%  Create a fit.
%
%  Data for 'muscle_force' fit:
%      X Input : p
%      Y Input : h
%      Z Output: F
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Jun-2016 14:55:10


%% Fit: 'muscle_force'.
load('MuscleData.mat');
[xData, yData, zData] = prepareSurfaceData( p, h, F );

% Set up fittype and options.
ft = fittype( 'loess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Robust = 'Bisquare';

% Fit model to data.
muscle_func_fit = fit( [xData, yData], zData, ft, opts );

