function M = Mfunc2(in1)
%MFUNC2
%    M = MFUNC2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    16-Jun-2016 17:47:42

M = reshape([1.0./6.0e1,0.0,0.0,0.0,1.0./6.0e1,0.0,0.0,0.0,1.0./6.0e1],[3,3]);
