function M = Mfunc2(in1)
%MFUNC2
%    M = MFUNC2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    13-Jun-2016 17:14:11

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
M = reshape([q1.*1.5e3-2.399833333333333e2,0.0,0.0,0.0,q2.*1.5e3-2.399833333333333e2,0.0,0.0,0.0,q3.*1.5e3-2.399833333333333e2],[3,3]);
